baseURL = "https://www.profvincent.com"
theme = "hermit-v2"
enableRobotsTXT = true ## set to true to enable inbuilt robots.txt

languageCode = "en-us"

title = "Prof. Vincent"
enableGitInfo = true

rssLimit = 10

copyright = "(c) 2025 by Laurence Vincent"
enableEmoji = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]


[params.author]
  name = "Larry Vincent"
  about = "Professor of the Practice of Marketing, USC Marshall School of Business"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.
  # category = "categories"

# Enable to get proper Mathjax support
#[markup]
#  [markup.goldmark]
#    [markup.goldmark.extensions]
#      [markup.goldmark.extensions.passthrough]
#        enable = true
#        [markup.goldmark.extensions.passthrough.delimiters]
#          block = [['\[', '\]'], ['$$', '$$']]
#          inline = [['\(', '\)']]


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "Central location for lecture material used by Larry Vincent."
  # images = [""]
  themeColor = "#FDCA49"
  accentColor = "#018472"

  homeSubtitle = "Larry Vincent, USC Marshall School of Business"
  footerCopyright = "All rights reserved."
  footerHideThemeName = true
  # bgImg = ""
  # gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = false
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = "CHANGE ME READ TIME"
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "⊲"
  # pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  # descriptionInPosts= true
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]
  # noIndex = false
  # denyRobots = "noindex, nofollow, noarchive"
  # allowRobots = "index, follow"
  # siteNoIndex = false
  # noIndexPages = ["404 Page not found"]
  # usesAnimation = true
  
 
  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/LarryVincent"

 [[params.socialLinks]]
    name = "linkedin"
    url = "https://linkedin.com/in/laurencevincent"


[menu]
